Fix missing wallet variable in handleAccept function
Error: Cannot find name 'wallet'
Fix: Added wallet to destructured useStore values

The handleAccept function was using wallet.address and wallet.chainId
but wallet wasn't included in the useStore destructuring.